const numberButtons = document.querySelectorAll('[data-number]')
const operationButtons = document.querySelectorAll('[data-operation]')
const clearButton = document.querySelector('[data-clear]')
const equalButton = document.querySelector('[data-equal]')
const deleteButton = document.querySelectorAll('[data-delete]')
const previousTextElement =document.querySelector('[data-previous]')
const currentTextElement =document.querySelector('[data-current]')
